<?php

namespace AppBundle\Repository;

/**
 * EducationCenterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EducationCenterRepository extends \Doctrine\ORM\EntityRepository
{
}
