<?php

namespace AppBundle\Repository;

/**
 * PortfolioEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortfolioEntryRepository extends \Doctrine\ORM\EntityRepository
{
}
