<?php

namespace AppBundle\Repository;

/**
 * TechSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TechSkillRepository extends \Doctrine\ORM\EntityRepository
{
}
