app_profile:
    resource: "@AppBundle/Controller/ProfileController.php"
    type:     annotation

app_skill:
    resource: "@AppBundle/Controller/SkillController.php"
    type:     annotation

app_project:
    resource: "@AppBundle/Controller/ProjectController.php"
    type:     annotation

app_job:
    resource: "@AppBundle/Controller/JobController.php"
    type:     annotation

app_image:
    resource: "@AppBundle/Controller/ImageController.php"
    type:     annotation

app_education_center:
    resource: "@AppBundle/Controller/EducationCenterController.php"
    type:     annotation

app_education:
    resource: "@AppBundle/Controller/EducationController.php"
    type:     annotation

app_country:
    resource: "@AppBundle/Controller/CountryController.php"
    type:     annotation

app_company:
    resource: "@AppBundle/Controller/CompanyController.php"
    type:     annotation

app_city:
    resource: "@AppBundle/Controller/CityController.php"
    type:     annotation

app_certification:
    resource: "@AppBundle/Controller/CertificationController.php"
    type:     annotation

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /%locale%/
        permanent: true

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /{_locale}/
    requirements:
        _locale: es|en

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    requirements:
        _locale: es|en

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    requirements:
        _locale: es|en

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: es|en


