# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path:   fos_user_security_login
                check_path:   fos_user_security_check
                csrf_token_generator: security.csrf.token_manager
                default_target_path: admin_homepage

            logout:
                path: fos_user_security_logout
            anonymous:    true

    access_control:
        - { path: ^/[^/]+/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[^/]+/register, role: ROLE_SUPER_ADMIN }
        - { path: ^/[^/]+/resetting, role: ROLE_SUPER_ADMIN }
        - { path: ^/[^/]+/admin, role: ROLE_USER }
        - { path: ^/[^/]+/, role: IS_AUTHENTICATED_ANONYMOUSLY }


        # activate different ways to authenticate

        # http_basic: ~
        # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

        # form_login: ~
        # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
